//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Call4Pizza_reservation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class call4PizzaDb : DbContext
    {
        public call4PizzaDb()
            : base("name=call4PizzaDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ingredient> Ingredient { get; set; }
        public virtual DbSet<Meal> Meal { get; set; }
        public virtual DbSet<MealComposition> MealComposition { get; set; }
        public virtual DbSet<MealConstraints> MealConstraints { get; set; }
        public virtual DbSet<MealsOrder> MealsOrder { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<MealsGroup> MealsGroup { get; set; }
        public virtual DbSet<MealsGroupConstraints> MealsGroupConstraints { get; set; }
    }
}
