//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Call4Pizza_reservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        public Meal()
        {
            this.MealComposition = new HashSet<MealComposition>();
            this.MealsOrder = new HashSet<MealsOrder>();
            this.MealConstraints = new HashSet<MealConstraints>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public double basePrice { get; set; }
        public string description { get; set; }
        public Nullable<int> mealOriginId { get; set; }
        public int mealsGroupId { get; set; }
    
        public virtual ICollection<MealComposition> MealComposition { get; set; }
        public virtual ICollection<MealsOrder> MealsOrder { get; set; }
        public virtual ICollection<MealConstraints> MealConstraints { get; set; }
        public virtual MealsGroup MealsGroup { get; set; }
    }
}
