//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Call4Pizza_reservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealComposition
    {
        public int mealId { get; set; }
        public int ingredientId { get; set; }
        public int ingredientAmount { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Meal Meal { get; set; }
    }
}
