//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Call4Pizza_reservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealsGroup
    {
        public MealsGroup()
        {
            this.Meal = new HashSet<Meal>();
            this.MealsGroupConstraints = new HashSet<MealsGroupConstraints>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<Meal> Meal { get; set; }
        public virtual ICollection<MealsGroupConstraints> MealsGroupConstraints { get; set; }
    }
}
